2019/03/22 15:08:26 [error] [exception.CException] exception 'CException' with message 'Property "CUrlManager.sensitiveCase" is not defined.' in C:\xampp\htdocs\yii-1.1.20\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.20\framework\YiiBase.php(227): CComponent->__set('sensitiveCase', false)
#1 C:\xampp\htdocs\yii-1.1.20\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\yii-1.1.20\framework\base\CApplication.php(531): CModule->getComponent('urlManager')
#3 C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php(140): CApplication->getUrlManager()
#4 C:\xampp\htdocs\yii-1.1.20\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\shadow_dancer\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/shadow_dancer/index.php?r=site/page&view=about
HTTP_REFERER=http://localhost/shadow_dancer/
---
2019/03/22 15:08:39 [error] [exception.CException] exception 'CException' with message 'Property "CUrlManager.sensitiveCase" is not defined.' in C:\xampp\htdocs\yii-1.1.20\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.20\framework\YiiBase.php(227): CComponent->__set('sensitiveCase', false)
#1 C:\xampp\htdocs\yii-1.1.20\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\yii-1.1.20\framework\base\CApplication.php(531): CModule->getComponent('urlManager')
#3 C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php(140): CApplication->getUrlManager()
#4 C:\xampp\htdocs\yii-1.1.20\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\shadow_dancer\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/shadow_dancer/
---
2019/03/23 00:15:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yii-1.1.20\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\shadow_dancer\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/shadow_dancer/index.php?r=gii
---
2019/03/23 00:36:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yii-1.1.20\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\shadow_dancer\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/shadow_dancer/?r=gii
---
2019/03/24 03:35:27 [error] [exception.CException] exception 'CException' with message 'Property "CDbConnection.connectionStrin" is not defined.' in C:\xampp\htdocs\yii-1.1.20\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.20\framework\YiiBase.php(227): CComponent->__set('connectionStrin', 'mysql:host=loca...')
#1 C:\xampp\htdocs\yii-1.1.20\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\yii-1.1.20\framework\base\CModule.php(103): CModule->getComponent('db')
#3 C:\xampp\htdocs\yii-1.1.20\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#4 C:\xampp\htdocs\yii-1.1.20\framework\web\CFormModel.php(39): ModelCode->init()
#5 C:\xampp\htdocs\yii-1.1.20\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#6 C:\xampp\htdocs\yii-1.1.20\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#7 C:\xampp\htdocs\yii-1.1.20\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#8 C:\xampp\htdocs\yii-1.1.20\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii-1.1.20\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii-1.1.20\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#13 C:\xampp\htdocs\yii-1.1.20\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\shadow_dancer\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/shadow_dancer/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/shadow_dancer/index.php?r=gii/model/index
---
2019/03/24 03:35:43 [error] [exception.CException] exception 'CException' with message 'Property "CDbConnection.connectionStrin" is not defined.' in C:\xampp\htdocs\yii-1.1.20\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.20\framework\YiiBase.php(227): CComponent->__set('connectionStrin', 'mysql:host=loca...')
#1 C:\xampp\htdocs\yii-1.1.20\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\yii-1.1.20\framework\base\CModule.php(103): CModule->getComponent('db')
#3 C:\xampp\htdocs\yii-1.1.20\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#4 C:\xampp\htdocs\yii-1.1.20\framework\web\CFormModel.php(39): ModelCode->init()
#5 C:\xampp\htdocs\yii-1.1.20\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#6 C:\xampp\htdocs\yii-1.1.20\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#7 C:\xampp\htdocs\yii-1.1.20\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#8 C:\xampp\htdocs\yii-1.1.20\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii-1.1.20\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii-1.1.20\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#13 C:\xampp\htdocs\yii-1.1.20\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\shadow_dancer\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/shadow_dancer/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/shadow_dancer/index.php?r=gii
---
2019/03/24 03:36:01 [error] [exception.CException] exception 'CException' with message 'Property "CDbConnection.connectionStrin" is not defined.' in C:\xampp\htdocs\yii-1.1.20\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.20\framework\YiiBase.php(227): CComponent->__set('connectionStrin', 'mysql:host=loca...')
#1 C:\xampp\htdocs\yii-1.1.20\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\yii-1.1.20\framework\base\CModule.php(103): CModule->getComponent('db')
#3 C:\xampp\htdocs\yii-1.1.20\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#4 C:\xampp\htdocs\yii-1.1.20\framework\web\CFormModel.php(39): ModelCode->init()
#5 C:\xampp\htdocs\yii-1.1.20\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#6 C:\xampp\htdocs\yii-1.1.20\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#7 C:\xampp\htdocs\yii-1.1.20\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#8 C:\xampp\htdocs\yii-1.1.20\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii-1.1.20\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii-1.1.20\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#13 C:\xampp\htdocs\yii-1.1.20\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\shadow_dancer\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/shadow_dancer/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/shadow_dancer/index.php?r=gii
---
2019/03/24 03:36:03 [error] [exception.CException] exception 'CException' with message 'Property "CDbConnection.connectionStrin" is not defined.' in C:\xampp\htdocs\yii-1.1.20\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.20\framework\YiiBase.php(227): CComponent->__set('connectionStrin', 'mysql:host=loca...')
#1 C:\xampp\htdocs\yii-1.1.20\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\yii-1.1.20\framework\base\CModule.php(103): CModule->getComponent('db')
#3 C:\xampp\htdocs\yii-1.1.20\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#4 C:\xampp\htdocs\yii-1.1.20\framework\web\CFormModel.php(39): ModelCode->init()
#5 C:\xampp\htdocs\yii-1.1.20\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#6 C:\xampp\htdocs\yii-1.1.20\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#7 C:\xampp\htdocs\yii-1.1.20\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#8 C:\xampp\htdocs\yii-1.1.20\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii-1.1.20\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii-1.1.20\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#13 C:\xampp\htdocs\yii-1.1.20\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\shadow_dancer\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/shadow_dancer/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/shadow_dancer/index.php?r=gii
---
2019/03/24 03:36:04 [error] [exception.CException] exception 'CException' with message 'Property "CDbConnection.connectionStrin" is not defined.' in C:\xampp\htdocs\yii-1.1.20\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.20\framework\YiiBase.php(227): CComponent->__set('connectionStrin', 'mysql:host=loca...')
#1 C:\xampp\htdocs\yii-1.1.20\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\yii-1.1.20\framework\base\CModule.php(103): CModule->getComponent('db')
#3 C:\xampp\htdocs\yii-1.1.20\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#4 C:\xampp\htdocs\yii-1.1.20\framework\web\CFormModel.php(39): ModelCode->init()
#5 C:\xampp\htdocs\yii-1.1.20\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#6 C:\xampp\htdocs\yii-1.1.20\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#7 C:\xampp\htdocs\yii-1.1.20\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#8 C:\xampp\htdocs\yii-1.1.20\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii-1.1.20\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii-1.1.20\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#13 C:\xampp\htdocs\yii-1.1.20\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\shadow_dancer\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/shadow_dancer/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/shadow_dancer/index.php?r=gii
---
2019/03/24 03:44:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "login_user".' in C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php(141): CWebApplication->runController('login_user')
#1 C:\xampp\htdocs\yii-1.1.20\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\shadow_dancer\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/shadow_dancer/index.php?r=login_user
---
2019/03/24 03:55:44 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'apotek_k-24.pendaftarananggota' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `PendaftaranAnggota`.
in C:\xampp\htdocs\shadow_dancer\index.php (13)
2019/03/24 07:00:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "login_user".' in C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php(141): CWebApplication->runController('login_user')
#1 C:\xampp\htdocs\yii-1.1.20\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\shadow_dancer\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/shadow_dancer/?r=login_user
---
2019/03/24 07:01:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "login_user".' in C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php(141): CWebApplication->runController('login_user')
#1 C:\xampp\htdocs\yii-1.1.20\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\shadow_dancer\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/shadow_dancer/?r=login_user
---
2019/03/24 07:01:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "Login_User".' in C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php(141): CWebApplication->runController('Login_User')
#1 C:\xampp\htdocs\yii-1.1.20\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\shadow_dancer\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/shadow_dancer/?r=Login_User
---
2019/03/24 07:01:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "login_user".' in C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php(141): CWebApplication->runController('login_user')
#1 C:\xampp\htdocs\yii-1.1.20\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\shadow_dancer\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/shadow_dancer/index.php?r=login_user
---
2019/03/24 07:03:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "login_user".' in C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php(141): CWebApplication->runController('login_user')
#1 C:\xampp\htdocs\yii-1.1.20\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\shadow_dancer\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/shadow_dancer/index.php?r=login_user
---
2019/03/24 08:05:35 [error] [exception.CException] exception 'CException' with message 'SiteController cannot find the requested view "_form".' in C:\xampp\htdocs\yii-1.1.20\framework\web\CController.php:881
Stack trace:
#0 C:\xampp\htdocs\shadow_dancer\protected\views\site\login.php(74): CController->renderPartial('_form', Array)
#1 C:\xampp\htdocs\yii-1.1.20\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\yii-1.1.20\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#3 C:\xampp\htdocs\yii-1.1.20\framework\web\CController.php(872): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\yii-1.1.20\framework\web\CController.php(785): CController->renderPartial('login', Array, true)
#5 C:\xampp\htdocs\shadow_dancer\protected\controllers\SiteController.php(98): CController->render('login', Array)
#6 C:\xampp\htdocs\yii-1.1.20\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii-1.1.20\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii-1.1.20\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii-1.1.20\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\yii-1.1.20\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\yii-1.1.20\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\shadow_dancer\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/shadow_dancer/index.php?r=site/login
HTTP_REFERER=http://localhost/shadow_dancer/index.php?r=site/index
---
